### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by yuanf225** [milestorme/mod-bounty-hunter#2]
/www/game/azerothcore-wotlk/modules/mod-bounty-hunter/src/BountyHunter.cpp:333:6: warning: ignoring return value of function declared with pure
      attribute [-Wunused-value]
                                        toupper(code[0]);
                                        ^~~~~~~ ~~~~~~~
/www/game/azerothcore-wotlk/modules/mod-bounty-hunter/src/BountyHunter.cpp:327:54: warning: unused parameter 'pCreature' [-Wunused-parameter]
                bool OnGossipSelectCode(Player* pPlayer, Creature* pCreature, uint32 uiSender, uint32 uiAction, const char * code)

Is there time to fix it

**Comment by milestorme** [comment]
It’s just a warning , should still work
